server:
  port: 8082
#resolved up problems
spring:
  application:
      name: payment-service
  boot:
    admin:
      url: http://${eureka.instance.hostname}:9002
  zipkin:
    base-url: http://${eureka.instance.hostname}:9001
  #mysql database config
  datasource:
    url: jdbc:mysql://localhost:3306/micro_payment?useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull
    #use jasypt to encrypt username/password
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
     # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 1
    minIdle: 1
    maxIdle: 5
    maxActive: 50
    maxWait: 10000
    timeBetweenEvictionRunsMillis: 10000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    filters: stat

    mapperLocations: classpath:mapper/*.xml
    typeAliasPackage: com.splendid.common.bean
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:9003/eureka/
#    register-with-eureka: false
#    fetch-registry: false

jasypt:
  encryptor:
    password: EbfYkitulv73I2p0mXI50JMXoaxZTKJ7
#pagehelper
pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
  params: count=countSql
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.splendid.common.bean
management:
  security:
    enabled: false

