server:
  port: 9002
eureka:
  instance:
    hostname: localhost
logging:
  level:
    tk:
      mybatis: TRACK
spring:
  application:
    name: SpringBootAdminServer
  boot:
    admin:
      url: http://${eureka.instance.hostname}:${server.port}
  jackson:
    serialization:
      indent_output: true
  mvc:
    view:
      prefix: /templates/
      suffix: .ftl
  freemarker:
    cache: false
    request-context-attribute: request
  output:
    ansi:
      enabled: always

